import errno
import json
import os
import platform
import socket
import time

HOST = os.environ.get("TARGET_HOST", "server")
PORT = int(os.environ.get("TARGET_PORT", "9000"))
TIMEOUT_SECONDS = float(os.environ.get("SOCKET_TIMEOUT_SECONDS", "2"))

EXPERIMENT_ID = "experiment.network.connection_reset.python_linux"
CLAIM_ID = "claim.network.connection_reset.peer_rst_surfaces_econnreset"


def normal_roundtrip():
    started = time.monotonic()
    with socket.create_connection((HOST, PORT), timeout=TIMEOUT_SECONDS) as connection:
        connected_ms = (time.monotonic() - started) * 1000.0
        connection.sendall(b"ping")
        payload = connection.recv(16)
    return {
        "connected": True,
        "connect_ms": connected_ms,
        "response": payload.decode("ascii", errors="replace"),
    }


def reset_roundtrip():
    started = time.monotonic()
    connection = socket.create_connection((HOST, PORT), timeout=TIMEOUT_SECONDS)
    connected_ms = (time.monotonic() - started) * 1000.0
    phase = "send"
    try:
        connection.sendall(b"reset")
        phase = "receive"
        time.sleep(0.05)
        payload = connection.recv(16)
        return {
            "connected": True,
            "connect_ms": connected_ms,
            "phase": phase,
            "received_bytes": len(payload),
            "transport_error": None,
            "errno": None,
        }
    except OSError as exc:
        return {
            "connected": True,
            "connect_ms": connected_ms,
            "phase": phase,
            "received_bytes": None,
            "transport_error": errno.errorcode.get(exc.errno, type(exc).__name__),
            "errno": exc.errno,
            "error_class": type(exc).__name__,
            "message": str(exc),
        }
    finally:
        try:
            connection.close()
        except OSError:
            pass


baseline = normal_roundtrip()
intervention = reset_roundtrip()
recovery = normal_roundtrip()

assertions = {
    "baseline_peer_is_reachable": baseline.get("response") == "pong",
    "tcp_connection_established_before_reset": intervention.get("connected") is True,
    "client_observes_econnreset": intervention.get("errno") == errno.ECONNRESET,
    "recovery_peer_is_reachable": recovery.get("response") == "pong",
}
result = "supports" if all(assertions.values()) else "inconclusive"

evidence = {
    "schema_version": "0.1",
    "kind": "empirical_evidence",
    "experiment": EXPERIMENT_ID,
    "claims": [CLAIM_ID],
    "environment": {
        "runtime": "python",
        "runtime_version": platform.python_version(),
        "platform": platform.platform(),
        "isolation": "docker_compose",
        "operating_system": "linux",
    },
    "intervention": {
        "action": "peer_abortive_close_with_so_linger_zero",
        "target_host": HOST,
        "target_port": PORT,
    },
    "observations": {
        "baseline": baseline,
        "intervention": intervention,
        "recovery": recovery,
    },
    "assertions": assertions,
    "result": result,
    "interpretation": "The same reachable TCP peer answers normally before and after the intervention. During intervention it accepts the connection and performs an abortive close with SO_LINGER(1,0), causing Linux to surface ECONNRESET to the client rather than an application-protocol response.",
    "limitations": [
        "The reset is generated by a controlled peer in Docker on Linux.",
        "Real resets may originate from the peer kernel, application, proxy, load balancer, NAT, firewall, or another intermediary.",
        "The experiment does not cover refusal, timeout, DNS, TLS, packet loss, or application-protocol errors.",
    ],
}
print(json.dumps(evidence))
