import errno
import json
import os
import platform
import socket
import time

HOST = os.environ.get("TARGET_HOST", "server")
OPEN_PORT = int(os.environ.get("OPEN_PORT", "9000"))
CLOSED_PORT = int(os.environ.get("CLOSED_PORT", "9001"))
TIMEOUT_SECONDS = float(os.environ.get("SOCKET_TIMEOUT_SECONDS", "2"))

EXPERIMENT_ID = "experiment.network.connection_refused.python_linux"
CLAIM_ID = "claim.network.connection_refused.closed_port_surfaces_econnrefused"


def normal_roundtrip():
    started = time.monotonic()
    with socket.create_connection((HOST, OPEN_PORT), timeout=TIMEOUT_SECONDS) as connection:
        connect_ms = (time.monotonic() - started) * 1000.0
        connection.sendall(b"ping")
        payload = connection.recv(16)
    return {
        "connected": True,
        "connect_ms": connect_ms,
        "response": payload.decode("ascii", errors="replace"),
    }


def refused_connection():
    started = time.monotonic()
    try:
        connection = socket.create_connection((HOST, CLOSED_PORT), timeout=TIMEOUT_SECONDS)
        connect_ms = (time.monotonic() - started) * 1000.0
        connection.close()
        return {
            "connected": True,
            "connect_ms": connect_ms,
            "phase": "connect",
            "transport_error": None,
            "errno": None,
        }
    except OSError as exc:
        return {
            "connected": False,
            "connect_ms": (time.monotonic() - started) * 1000.0,
            "phase": "connect",
            "transport_error": errno.errorcode.get(exc.errno, type(exc).__name__),
            "errno": exc.errno,
            "error_class": type(exc).__name__,
            "message": str(exc),
        }


baseline = normal_roundtrip()
intervention = refused_connection()
recovery = normal_roundtrip()

assertions = {
    "baseline_peer_is_reachable": baseline.get("response") == "pong",
    "connection_never_establishes_on_closed_port": intervention.get("connected") is False,
    "failure_occurs_during_connect": intervention.get("phase") == "connect",
    "client_observes_econnrefused": intervention.get("errno") == errno.ECONNREFUSED,
    "recovery_peer_is_reachable": recovery.get("response") == "pong",
}
result = "supports" if all(assertions.values()) else "inconclusive"

evidence = {
    "schema_version": "0.1",
    "kind": "empirical_evidence",
    "experiment": EXPERIMENT_ID,
    "claims": [CLAIM_ID],
    "environment": {
        "runtime": "python",
        "runtime_version": platform.python_version(),
        "platform": platform.platform(),
        "isolation": "docker_compose",
        "operating_system": "linux",
    },
    "intervention": {
        "action": "connect_to_same_reachable_peer_on_closed_tcp_port",
        "target_host": HOST,
        "known_open_port": OPEN_PORT,
        "closed_port": CLOSED_PORT,
    },
    "observations": {
        "baseline": baseline,
        "intervention": intervention,
        "recovery": recovery,
    },
    "assertions": assertions,
    "result": result,
    "interpretation": "The peer host is proven reachable through a normal listening port before and after intervention. Connecting to a closed port on that same peer fails during TCP establishment with ECONNREFUSED, distinguishing refusal from a reset after establishment or a silent timeout.",
    "limitations": [
        "The refusal is generated by a closed TCP port in a Docker network on Linux.",
        "Real refusals may originate from the destination kernel, firewall policy, proxy, service lifecycle, or another component.",
        "The experiment does not cover reset after establishment, timeout, DNS, TLS, packet loss, or application-protocol errors.",
    ],
}
print(json.dumps(evidence))
